- hosts: all
  roles:
    - role: base_hardening
    - role: docker_runtime
    - role: wireguard
    - role: traefik

- hosts: postgres
  roles:
    - role: etcd
    - role: postgres

- hosts: garage_all
  roles:
    - role: garage

- hosts: ushahidi_all
  roles:
    - role: ushahidi
