- hosts: all
  roles:
    - role: base_hardening
    - role: docker_runtime
    - role: wireguard

- hosts: postgres
  roles:
    - role: postgres

- hosts: garage_all
  roles:
    - role: garage

- hosts: app_servers
  roles:
    - role: traefik
    - role: ushahidi
