- name: Create MinIO dir
  file: { path: /opt/minio, state: directory }

- name: Drop MinIO compose
  template:
    src: docker-compose.yml.j2
    dest: /opt/minio/docker-compose.yml

- name: Up MinIO
  community.docker.docker_compose_v2:
    project_src: /opt/minio
    state: present
